export enum OrderType {
  RETRIEVE_ALL = "RETRIEVE_ALL",
  RETRIEVE_SINGLE_ORDER = "RETRIEVE_SINGLE_ORDER",
  ADD = "ADD",
  EDIT = "EDIT",
  DELETE = "DELETE",
  CLEAR_ORDERS = "CLEAR_ORDERS",
  ERROR = "ERROR"
}