export enum ProductType {
  RETRIEVE_ALL = "RETRIEVE_ALL",
  RETRIEVE_SINGLE_PRODUCT = "RETRIEVE_SINGLE_PRODUCT",
  ADD = "ADD",
  EDIT = "EDIT",
  DELETE = "DELETE",
  CLEAR_PRODUCTS = "CLEAR_PRODUCTS",
  ERROR = "ERROR"
}